config/routes.rb
Rails.application.routes.draw do
  resources :managements
  get 'home/top'
  devise_for :admins
  root to: "home#top"
  get '/office',to:'home#office'
  get '/remote',to:'home#remote'
  get '/mtg',to:'home#mtg'
  get '/holiday',to:'home#holiday'
  get '/home',to:'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/management.rb
class Management < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!
  #after_filter:after_login, :only=>:test
  def test
  end

  # private
  #
  # def after_login
  #   current_user.update(first_sign_in_at: current_user.current_sign_in_at) unless current_user.first_sign_in_at
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :set_management, only: [:office,:remote,:mtg,:holiday,:home]
    after_action :save, only: [:office,:remote,:mtg,:holiday,:home]
  def top
    @admins = Admin.all
    @d = Date.current
  end

  def office
    @admin.place = 'office'
    redirect_to root_path
  end

  def remote
    @admin.place = "remote"
    redirect_to root_path
  end

  def mtg
    @admin.place = 'mtg'
    redirect_to root_path
  end

  def holiday
    @admin.place = 'holiday'
    redirect_to root_path
  end

  def home
    @admin.place = 'home'
    redirect_to root_path
  end

  def manager
    @admins = Admin.all
  end


  private

  def set_management
    @admin = current_admin
  end

  def save
    @admin.save

  end

  def admin_params
    params.require(:admin).permit(:office)
   end
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  before_action :set_management, only: [:show, :edit, :update, :destroy]

  # GET /managements
  # GET /managements.json
  def index
    if current_admin.role != 'leader'
      redirect_to '/home/top'
    end
    @admins = Admin.all
  end

  # GET /managements/1
  # GET /managements/1.json
  def show
  end

  # GET /managements/new
  def new
    @admin = Admin.new
  end

  # GET /managements/1/edit
  def edit
  end

  # POST /managements
  # POST /managements.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to managements_path, notice: 'Management was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new}
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managements/1
  # PATCH/PUT /managements/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to management_path(@admin), notice: 'Management was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managements/1
  # DELETE /managements/1.json
  def destroy
    @management.destroy
    respond_to do |format|
      format.html { redirect_to managements_url, notice: 'Management was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_management
      @admin = Admin.find(params[:id])
      @management = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:name, :email,:password,:role)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/manages_helper.rb
module ManagesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/views/home/manager.html.erb
<p id="notice"><%= notice %></p>

<h1>Manager</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>Email</th>
      <th>password</th>
      <th>role</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_management_path(admin) %></td>
        <td><%= link_to 'Destroy', admin , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Management', new_admin_path %>
<%= link_to '戻る','../' %>

app/views/home/top.html.erb
<h1>Team Fake </h1>
  <table align="center">
     <h2><%= @d %></h2>

      <% @admins.each do |admin| %>
      <tr>
          <th><%= admin.name %></th>
            <td><%= admin.place %></td>
            </tr>
      <% end %>
      </table>
      <div class="main-wrapper">
        <%= link_to office_path do %>
          <i class="material-icons">office</i>
        <% end %>
        <%= link_to remote_path do  %>
        <i class="material-icons">remote</i>
        <% end %>
        <%= link_to mtg_path do  %>
        <i class="material-icons">mtg</i>
          <% end %>
        <%= link_to holiday_path do  %>
        <i class="material-icons">holiday</i>
          <% end %>
        <%= link_to home_path do  %>
        <i class="material-icons">home</i>
          <% end %>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<% if notice %>
  <p class="notice"><%= notice %></p>

<% end %>
<html>
  <head>
    <title>Checker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <%= yield %>


  </body>
  <% if admin_signed_in? %>
  <p><%= link_to "sign out", destroy_admin_session_path, method: :delete %></p>
    <p><%= link_to 'leader only', managements_path %></p>
<% end %>
</html>

app/views/managements/_form.html.erb
<%= form_with(model: @admin, local: true,url: url) do |form| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this management from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :leader %>
    <%= form.radio_button :role ,'leader' %>
    <%= form.label :member %>
    <%= form.radio_button :role ,'member' %>


  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/managements/edit.html.erb
<h1>Editing Management</h1>

<%= render 'form', admin: @admin, url:management_path(@admin)%>

<p><%= link_to 'Show', management_path(@admin) %></p>
<p><%= link_to 'Back', managements_path %></p>

app/views/managements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Managements</h1>
<table>
  <thead>
    <tr>
      <th>name</th>
      <th>Email</th>
      <th>role</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%= admin.role %></td>
        <td><%= link_to 'Show', management_path(admin)%></td>
        <td><%= link_to 'Edit', edit_management_path(admin) %></td>
        <td><%= link_to 'Destroy', management_path(admin), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Management', new_management_path %></p>
<p><%= link_to 'back','../' %></p>

app/views/managements/new.html.erb
<h1>New Management</h1>

<%= render 'form', admin: @admin , url:managements_url %>

<p><%= link_to 'Back', managements_path %></p>

app/views/managements/show.html.erb
<p id="notice"><%= notice %></p>

  <strong>name:</strong>
  <%= @admin.name %>
  <br>

  <strong>email:</strong>
  <%= @admin.email %>
  <br>
  <strong>role:</strong>
  <%= @admin.role %>
  <br>

<p><%= link_to 'Edit', edit_management_path(@admin) %></p>
<p><%= link_to 'Back', managements_path %></p>